### ISSUE TITLE
Some bugs I found

### ISSUE THREAD

**Issue by leddy231** [mr-chibi/player_shops#1]
Hi!
Truly amazing datapack, we are currently testing it before adding it to our server.
Some bugs I have noticed that would be nice if they are fixed

### Enchantment/NBT dupe
It seems the shop remembers previous items NBT data, and merges it into new items
Steps to reproduce:
1. Add item with Enchantment/any other data as buy currency
2. Perform one trade
3. Switch currency item for one without data
4. Perform one trade
5. The item used to set currency now has the previous enchanted items data
I managed to fix this by changing  ... HandItems[0].tag.ps_inventory[1] _merge_ from block...   
to ... HandItems[0].tag.ps_inventory[1] _set_ from block... in nbt.functions

### Bedrock breaking
Since the shop simply replaces two blocks with chests they can be used to destroy bedrock, and potentially other protected blocks (for example in a players home). Could there instead be a check used to summon the shop on two stacked chests that the player have placed manually?

### Output override
If you restock your trades without removing items from the output chest the contents of the output chest gets removed. this can be solved by the player adding a hopper under the output chest but it would be nice if there is a safeguard against this.

**Comment by backanda** [comment]
This one doesn't work in its current state from planetminecraft... normal players can access all chests and withdraw whatever they want.

**Comment by mr-chibi** [comment]
Sorry, for long awaited response on bug report. ^-^"
Been writing a new entire remaster version for 1.19.4 No, villagers required! No Double Chest required! Ton optimization features bug fixes and quality of life changes.
