### ISSUE TITLE
Current version not working?

### ISSUE THREAD

**Issue by backanda** [mr-chibi/player_shops#3]
This one doesn't work in its current state from planetminecraft, normal players can withdraw anything they want from any of the chests. Both on normal trader set up by me and admin trader.

**Comment by Amzd** [comment]
When the owner is closest to the chest, anyone can open it I think.

**Comment by mr-chibi** [comment]
New remastered version has everything condensed lot new features!
"Payments", "Chat GUI", "No more villagers!", "Working Lock/Unlock Mechanic!" and tons bug fixes :D

Still WIP, been keeping track of all bug reports and doing lot bug smashing new version unsure when I have a release date for yet due, but I do promise get rid all them naste bugs!
